config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'

  get 'user_sessions/crete'

  get 'user_sessions/destroy'

resources(:users, only: [:create, :destroy, :show, :new, :index]) do
    resources(:concerts, only: [:create, :destroy, :new, :index, :show])

end

  resources(:concerts, only: [:create, :destroy, :new, :index, :show]) do
    resources(:comments, only: [:create, :destroy, :new])
  end

  

  resources(:user_sessions, only: [:new, :create])

  root 'concerts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :concert
  belongs_to :user
  
end

app/models/concert.rb
class Concert < ActiveRecord::Base
	belongs_to :user
	has_many :comments, :dependent => :delete_all
	

	validates :artist, presence: true
	validates :venue, presence: true
	validates :city, presence: true
	validates :date, presence: true
	validates :price, presence: true
	validates :description, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :concerts
	has_many :comments
 
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true
  validates :password, :presence => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
  render :file => File.join(Rails.root, '/public/404'), :formats => [:html], :status => 404, :layout => false
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # def index
  # end

  # def new
  # 	@concert = Concert.find_by(id: params[:id])

  # 	@comment = @concert.comments.new
  # end

  def show
    @comment.user = User.find_by(id: params[:user_id])
  	@comments = Comment.find_by(id: params[:id])
  end

  def create
    @user = session[:user_id]

  	@concert = Concert.find_by(id: params[:concert_id])

  	@comment = @concert.comments.new(comment_params)

    @comment.user_id = @user

  	if @comment.save
  		redirect_to concert_path(@concert)
  	end
  end

  def destroy
  	@comments = Comment.find_by(id: params[:id])
  	
  	@comments.destroy

  	redirect_to concerts_path
  end

  private

  def comment_params
  	params.require(:comment).permit(:comment, :name)
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
  	@concerts = Concert.all
  	@concerts_today = @concerts.where(date: Date.today)
  	@concerts_this_month = @concerts.where('extract(month from date) = ?', Date.today.month)
    @user_id = session[:user_id]

  end

  def show
  	@concert = Concert.find_by(id: params[:id])
  	@deletecomment = Comment.find_by(id: params[:id])
  	@comments = @concert.comments.all
  	@comment = @concert.comments.new
    @user_id = session[:user_id]
    @user = User.find_by(email: params[:email])
  end

  def new
    @user = User.find_by(id: params[:user_id])
  	@concert = Concert.new
    @user_id = session[:user_id]

    if session[:user_id] == nil
      not_found
    end

  end

  def create
    @user = User.find_by(id: params[:user_id])

  	@concert = @user.concerts.new(concert_params)

    if @concert.save
      redirect_to concerts_path
    end

  	
  end

  def destroy
  	@comment = Comment.find_by(id: params[:id])

  	@concert = Concert.find_by(id: params[:id])
  	
  	@concert.destroy

  	redirect_to concerts_path
  end

  private

  def concert_params
    params.require(:concert).permit(:artist, :venue, :city, :date, :price, :description)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.find_by(params[:id])
	 @user_id = session[:user_id]


  	render 'new'


  end

  def create
  	user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    session[:email] = user.email
    session[:username] = user.username
    flash[:notice] = "Thanks for logging in!"
    redirect_to user_path(user)
    else
       flash[:notice] = "Incorrect E-mail or Password"
       render action: 'new'
    end
  end

  def destroy
  session[:user_id] = nil
   redirect_to concerts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
		@user = User.find_by(id: params[:id])

		@user_id = session[:user_id]

	end

	def new
	@user = User.new
	@user_id = session[:user_id]
	end

	def create
		@user_id = User.find_by(session[:id])
  		@user = User.new(
  			:username => params[:user][:username],
			:email => params[:user][:email],
			:password => params[:user][:password])
  respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        session[:username] = @user.username
        session[:email] = @user.email
        format.html { redirect_to user_path(@user), notice: 'Your account was created' }
        flash[:notice] = 'Your account was successfully created.'
      else
        format.html { render :new }
      end
    end
end
	def show
		@user = User.find_by(id: params[:id])
		@user_id = session[:user_id]

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new.html.erb
<%= form_for [@user, @concert, @comment] do |f| %>
	

	<br><br>
	<%= f.label 'Comment' %><br>
	<%= f.text_area 'comment', :class => 'comment-field', :required => true %>
	<br>
	<% if session[:user_id] == nil %>
	<%= f.submit 'Add Comment', :class => 'btn btn-info', :disabled => true %>
	<span><small>*You much sign in to comment!</small></span>
	<% else %>
		<%= f.submit 'Add Comment', :class => 'btn btn-info' %>
		<% end %>
	<hr class="hr">
	<% end %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/concerts/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 text-center header-content">
<h1>Upcoming Events</h1>
	<hr class="hr">
		</div>
	</div>


	<div class="row content-wrapper" style="padding-top: 0px;">
		<div class="col-sm-8 panel-default box-shadow--6dp" style="background-color: #F7F7F7; border-style: solid; border-radius: 5px; border-color: lightgray; border-width: 1px;">
			<h3>Today's Events</h3>
			<hr class="cool-underline" style="border-color: black;">
			<% @concerts_today.each do |x| %>
			<span class="index-title"><%= link_to x.artist, concert_path(x), :style => 'text-decoration: none; color: black;', :class => 'sliding-u-l-r' %></span>
			
			<% if session[:user_id] == x.user_id %>
			<%= link_to 'x', concert_path(x), method: :delete, :class => 'close' %>
			<% end %>

			<br>
				<span>@<b><%= x.city %></b></span>
				<br>
				<small class="date-info"><%= x.date.month %>/<%= x.date.day %>/<%= x.date.year %></small><span class="today"> TODAY!</span>
				<br>
				
				<br><br>
				<hr style="border-color: darkgray;">
			<% end %>
			<small class="more-info">Click an artist for more information</small>
			<br><br><br>
		</div>


		<div class="col-sm-4">
			<h3>Events This Month</h3>
			<hr class="cool-underline">
			<% @concerts_this_month.each do |x| %>
			<span class="index-title"><%= link_to x.artist, concert_path(x), :style => 'text-decoration: none; color: black;', :class => 'sliding-u-l-r-month' %></span>
			
			<% if session[:user_id] == x.user_id %>
			<%= link_to 'x', concert_path(x), method: :delete, :class => 'close' %>
			<% end %>

			<br>
				<span>@<b><%= x.city %></b></span>
				<br>
				<small class="date-info"><%= x.date.month %>/<%= x.date.day %>/<%= x.date.year %></small>
				<br>
				<br><br>
				<hr style="border-color: black;">
			<% end %>
		</div>
	</div>
</div> 

app/views/concerts/new.html.erb
<script type="text/javascript">

    $(window).load(function(){
        $('#myModal').modal('show');
    });

</script>


<% if session[:user_id].nil? %>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title text-center" id="myModalLabel" style="color: darkred;">Access Denied</h4>
      </div>
      <div class="modal-body text-center " style="color: gray;">
      	<p class="glyphicon glyphicon-ban-circle text-center" style="color: darkred; font-size: 25px;"></p><br>
      	<b>
        You have to be signed in to create an event!<br>
        Please either sign in or create an account.
    </b>
      </div>
      <div class="modal-footer">
        <%= link_to 'Login', new_user_session_path, :class => 'btn btn-default' %>
        <%= link_to 'Signup', new_user_path, :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

<% end %>

<div class="container new-concert">
	<div class="row concert-form">
		<div class="col-sm-3">
			<h3>Create A New Event</h3>
			<hr>
		</div>

		<div class="col-sm-4">
			<%= form_for [@user, @concert] do |f| %>
				<br>
				<%= f.label 'Artist' %>
				<br>
				<%= f.text_field 'artist', :class => 'form-field' %>
				<br><br>
				<%= f.label 'Venue' %>
				<br>
				<%= f.text_field 'venue', :class => 'form-field' %>
				<br><br>
				<%= f.label 'Where (City, State)' %>
				<br>
				<%= f.text_field 'city', :class => 'form-field' %>
				<br><br>
				<%= f.label 'Date' %>
				<br>
				<%= f.date_field 'date', :class => 'form-field', :style => 'color: black;' %>
				<br><br>
				<%= f.label 'Price' %>
				<br>
				<%= f.number_field :price, :step => 0.01, :class => 'form-field', :style => 'height: 35px;' %>
				<br><br>
				<%= f.label 'Description' %>
				<br>
				<%= f.text_field 'description', :class => 'form-field' %>
				<br><br>
				<%= f.submit 'Create', :class => 'btn btn-primary' %>
				<br><br>
				<% end %>
		</div>


	</div>
</div>

app/views/concerts/show.html.erb
<div class="container" style="padding-top: 50px;">
	<div class="row">
		<div class="col-sm-6">
			<h3><%= @concert.artist %></h3>
			
				<hr>
			<h4 class="where">Where </h4>
			<h5>@<%= @concert.venue %></h5>
			<h5><%= @concert.city %></h5>
			<br>
			<hr class="show-splits">
			<h4 class="where">When </h4>
			<h5><%= @concert.date.month %>/<%= @concert.date.day %>/<%= @concert.date.year %></h5>
			<br>
			<hr class="show-splits">
			<h4 class="where">Cost </h4>
			<h5>$<%= @concert.price %></h5>
			<%= link_to 'Buy Tickets!', concerts_path %>
			<br>
			<br><hr class="show-splits">
			<h4 class="where">Description</h4>
			<em><%= @concert.description %></em>
			<br><br>
			<span>Created by | <%= link_to @concert.user.username, user_path(@concert.user.id) %></span>
			<hr style="border-color: black;">
			<br><br>

			<i class="glyphicon glyphicon-play-circle play-circle"></i>
			<h4>Play a Demo of <%= @concert.artist %>'s Music</h4>
			<br><br>

		</div>

		<div class="col-sm-6">
			<%= render 'comments/new' %>

			<% @comments.each do |x| %>
				
				<b><%= x.user.username %></b> <%= link_to 'x', concert_comment_path(@concert, x), method: :delete, :class => 'close' %>
				<br>
				<span class="comment-content"><%= x.comment %></span>
				<hr class="show-splits">
				
				<br>
				<% end %>
				

		</div>
	</div>
</div> <!-- .container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcertApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

  <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


 
</head>
<body>


<% if session[:user_id] %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Potato</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if current_page?(concerts_path) %>">
            <%= link_to 'Home', concerts_path %><span class="sr-only">(current)</span>
        </li>
        <li class="<%= "active" if current_page?(user_path(@user_id)) %>">
            <%= link_to 'Profile', user_path(@user_id) %>
        </li>
      </ul>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
               <li><%= link_to 'New Event', new_user_concert_path(@user_id), :style => 'font-weight: bold;' %></li>

<li><%= link_to 'Logged in, ' + session[:username], user_path(session[:user_id]) %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'New Concert', new_user_concert_path(@user_id), :style => 'font-weight: bold;' %></li>
            <li><%= link_to 'My concerts', concerts_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "logout", :controller => "user_sessions", :action => "destroy" %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% else %>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Potato</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', concerts_path %><span class="sr-only">(current)</span></a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login | Signup <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_path, :style => 'font-weight: bold;' %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'About Us', concerts_path %></li>
            <li><%= link_to 'FAQ', concerts_path, :style => 'font-weight: bold;' %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% end %>



<%= yield %>

</body>
</html>

app/views/user_sessions/new.html.erb
<div class="loginform text-center">
<h1>Please Log In</h1>
<%= form_tag user_sessions_path do %>



 <div class="row">
            <div class="col-md-12">
               
                    
                    <div class="field">
    <%= label_tag :email, "Email Address" %><br>
    </div>
    
    <div class="field1">
    <%= text_field_tag :email, params[:email], class: "fields" %>
    </div>
    <br />
    
    <div class="field">
    <%= label_tag :password, "Password" %><br>
    </div>
    
    <div class="field1">
    <%= password_field_tag :password, nil, :class => "fields" %>
    </div>
    
    <br />
    
    <%= submit_tag "Log In", class: "btn btn-info" %>
    <br><br>
    <% if flash[:notice] %>
         <div class="popup">
             <div class="col-sm-10">
    <div id="notice"><%= flash[:notice] %></div>
    
        </div>
            </div>
                </div>
                    </div>
                        </div>
        <% end %>
    <% end %>

app/views/users/index.html.erb
<% @users.each do |x| %>
<% x.username %>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
<h1>Sign Up</h1>
  <%= form_for [@user] do |f| %>
    <%= f.label 'username' %> <br> <%= f.text_field 'username', :style => 'width: 20%;', :required => 'true' %> </p>
    <%= f.label 'email' %> <br> <%= f.text_field 'email', :style => 'width: 20%;', :required => 'true' %> </p>
   	<%= f.label 'password' %> <br> <%= f.password_field 'password', :style => 'width: 20%;', :required => 'true' %></p>
    <%= f.label 'password confirmation' %> <br> <%= f.password_field 'password', :style => 'width: 20%;', :required => 'true' %> <br><br>
    <%= f.submit :class => 'btn btn-info' %>
  <% end %>
  
</div>

app/views/users/show.html.erb
<html>
<head>

</head>
<body>
	<div class="container profile-container">
		<div class="row">
			<div class="col-md-12 text-center">
				<h1>Concert App Profile</h1>
			</div> <!-- first col-md-12 text-center -->
<% if session[:user_id] == @user.id %>
<p>Hey <%= session[:username] %>, this is your profile! :) </p>

<% else %>
<%= @user.username %><span>'s Profile</span>
<% end %>

		</div> <!-- first row -->
	</div> <!-- first container -->
</body>
</html>